export const LANGUAGES = [
  {id: "ar", name: "العربية"},
  {id: "de", name: "Deutsch"},
  {id: "el", name: "ελληνικά"},
  {id: "en", name: "English"},
  {id: "es", name: "Español"},
  {id: "fr", name: "Français"},
  {id: "he", name: "עברית"},
  {id: "hi", name: "हिन्दी"},
  {id: "it", name: "Italiano"},
  {id: "ja", name: "日本語"},
  {id: "ko", name: "한국어"},
  {id: "mn", name: "Монгол"},
  {id: "nl", name: "Nederlands"},
  {id: "ru", name: "Pyccĸий"},
  {id: "pt", name: "Português"},
  {id: "tr", name: "Tϋrkçe"},
  {id: "vi", name: "Tiếng Việt"},
  {id: "zh", name: "简化中国"}
];
